
-- 

CREATE TABLE `url` (
  `id` VARCHAR(36) NOT NULL,
  `short_url` VARCHAR(5) NOT NULL UNIQUE,
  `full_url` TEXT NOT NULL,
  `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_on` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
